// generated by borgogen - do not edit

export interface Blob {
  raw: string;
  alias: string;
  defined: string;
  arr: Array<number>;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/blob": { response: Blob };
  }
}

export {};
