// generated by borgogen - do not edit

export interface Ping {
  pong: string;
}

export interface Task {
  ID: number;
  CreatedAt: string;
  UpdatedAt: string;
  DeletedAt: string | null;
  title: string;
  body: string;
}

export interface TaskList {
  tasks: Array<Task>;
}

export interface TaskCreate {
  title: string;
  body: string;
}

export interface TaskItem {
  task: Task;
}

export interface Deleted {
  deleted: boolean;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/events": { response: unknown };
    "GET /api/ping": { response: Ping };
    "GET /api/tasks": { response: TaskList };
    "POST /api/tasks": { response: TaskItem; request: TaskCreate };
    "DELETE /api/tasks/{id}": { response: Deleted };
    "GET /api/tasks/{id}": { response: TaskItem };
  }
}

export {};
