// generated by borgogen - do not edit

export interface Task {
  ID: number;
  CreatedAt: string;
  UpdatedAt: string;
  DeletedAt: unknown;
  title: string;
  body: string;
}

export interface TaskList {
  tasks: Array<Task>;
}

export interface TaskItem {
  task: Task;
}

export interface Deleted {
  deleted: boolean;
}

declare module "borgo" {
  interface ApiRoutes {
    "GET /api/events": unknown;
    "GET /api/tasks": TaskList;
    "POST /api/tasks": TaskItem;
    "DELETE /api/tasks/{id}": Deleted;
    "GET /api/tasks/{id}": TaskItem;
  }
}

export {};
