// generated by borgogen - do not edit

export interface Status {
  ok: boolean;
}

export interface LibStatus {
  ready: boolean;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/local": { response: Status };
    "GET /api/remote": { response: LibStatus };
  }
}

export {};
