// generated by borgogen - do not edit

export interface Inner {
  a: number;
}

export interface Optional {
  bool?: boolean;
  num?: number;
  str?: string;
  slice?: Array<number>;
  map?: Record<string, number>;
  ptr?: number | null;
  iface?: unknown;
  a0?: Array<number>;
  a2?: Array<number>;
  st?: Inner;
  t?: string;
  m?: Inner;
  zerost?: Inner;
  zeronum?: number;
  zerotime?: string;
  typo: number;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/optional": { response: Optional };
  }
}

export {};
