// generated by borgogen - do not edit

export interface Pong {
  ok: boolean;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/ping": { response: Pong };
  }
}

export {};
