// Command borgogen statically analyzes an app's api/ package (go/ast +
// go/types, no runtime reflection) and generates two files:
//
//   - .borgo/api-types.d.ts - route pattern -> response and request types.
//     The response type of a route is the union of the T in every
//     borgo.JSON[T] and borgo.WriteJSON call reachable from its handler
//     (helper functions in the same package are followed); the request type
//     comes from borgo.Bind[T] and borgo.BindMax[T] calls the same way. A "//borgo:type Go TS"
//     directive overrides the mapping for any named Go type. borgo.PushT
//     calls additionally feed a "topic/event" -> payload map (WsEvents),
//     typing the browser's subscribe callback per topic.
//   - api/borgo.gen.go - mounting for handlers annotated with a
//     "//borgo:route METHOD /path" directive, so init() boilerplate is
//     optional. Manual borgo.Handle registration keeps working alongside.
package main

import (
	"fmt"
	"go/ast"
	"go/constant"
	"go/parser"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode"

	"golang.org/x/tools/go/packages"
)

const (
	borgoPath = "github.com/LuigiDavideMicca/borgo"
	genGoFile = "api/borgo.gen.go"
)

var (
	directiveRe    = regexp.MustCompile(`^//borgo:route\s+(.+)$`)
	typeRe         = regexp.MustCompile(`^//borgo:type\s+(\S+)\s+(.+)$`)
	patternRe      = regexp.MustCompile(`^(GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS) /\S*$`)
	looseDirective = regexp.MustCompile(`^//\s*borgo:route\b`)
)

type route struct {
	pattern string
	handler *types.Func
}

type genError struct{ msg string }

func fail(format string, args ...any) {
	panic(genError{fmt.Sprintf(format, args...)})
}

func main() {
	if err := run("."); err != nil {
		fmt.Fprintln(os.Stderr, "borgogen: "+err.Error())
		os.Exit(1)
	}
}

func run(root string) (err error) {
	defer func() {
		if r := recover(); r != nil {
			ge, ok := r.(genError)
			if !ok {
				panic(r)
			}
			err = fmt.Errorf("%s", ge.msg)
		}
	}()

	if _, statErr := os.Stat(filepath.Join(root, "api")); statErr != nil {
		fail("no api/ directory here; run borgogen from the app root")
	}

	// no NeedDeps: dependency types come from export data instead of a full
	// source re-typecheck of the import graph, which dominates wall time
	cfg := &packages.Config{
		Dir: root,
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax |
			packages.NeedTypes | packages.NeedTypesInfo | packages.NeedImports,
	}
	pkg := loadAPI(cfg, root)
	if hasErrorIn(pkg, "borgo.gen.go") {
		// the previous generated mounting references deleted handlers; retry
		// against an empty stub of it. only then: -overlay defeats the go
		// list cache and roughly triples the load
		genGoAbs, _ := filepath.Abs(filepath.Join(root, genGoFile))
		cfg.Overlay = map[string][]byte{genGoAbs: []byte("package " + apiPackageName(root) + "\n")}
		pkg = loadAPI(cfg, root)
	}
	if len(pkg.Errors) > 0 {
		msgs := make([]string, 0, len(pkg.Errors))
		for _, e := range pkg.Errors {
			msgs = append(msgs, e.Error())
		}
		fail("%s", strings.Join(msgs, "\n"))
	}
	dropGeneratedFile(pkg)

	routes := collectRoutes(pkg)
	decls := funcDecls(pkg)
	directives := collectDirectives(pkg, decls, routes)
	warnLooseRouteComments(pkg, decls)
	routes = append(routes, directives...)
	writeMounting(root, pkg.Name, directives, decls)

	sort.Slice(routes, func(i, j int) bool {
		am, ap := splitPattern(routes[i].pattern)
		bm, bp := splitPattern(routes[j].pattern)
		if ap != bp {
			return ap < bp
		}
		return am < bm
	})

	gen := &tsGen{
		names:     map[string]string{},
		taken:     map[string]bool{},
		apiPkg:    pkg.Types,
		overrides: collectTypeOverrides(pkg),
	}
	entries := make(map[string]string, len(routes))
	patterns := make([]string, 0, len(routes))
	for _, r := range routes {
		resp, req := gen.bridgeTypes(pkg, decls, decls[r.handler])
		entry := "{ response: " + resp
		if req != "" {
			entry += "; request: " + req
		}
		entries[r.pattern] = entry + " }"
		patterns = append(patterns, r.pattern)
	}

	wsKeys, wsEntries := collectPushes(pkg, gen)

	var out strings.Builder
	out.WriteString("// generated by borgogen - do not edit\n\n")
	for _, def := range gen.defs {
		out.WriteString(def)
		out.WriteString("\n")
	}
	out.WriteString("declare module \"borgo-framework\" {\n  interface ApiRoutes {\n")
	for _, p := range patterns {
		fmt.Fprintf(&out, "    %q: %s;\n", p, entries[p])
	}
	out.WriteString("  }\n")
	if len(wsKeys) > 0 {
		out.WriteString("  interface WsEvents {\n")
		for _, k := range wsKeys {
			fmt.Fprintf(&out, "    %q: %s;\n", k, wsEntries[k])
		}
		out.WriteString("  }\n")
	}
	out.WriteString("}\n\nexport {};\n")

	if mkErr := os.MkdirAll(filepath.Join(root, ".borgo"), 0o755); mkErr != nil {
		fail("%v", mkErr)
	}
	writeIfChanged(filepath.Join(root, ".borgo", "api-types.d.ts"), out.String())
	fmt.Printf("borgogen: %d routes -> .borgo/api-types.d.ts\n", len(patterns))
	return nil
}

func loadAPI(cfg *packages.Config, root string) *packages.Package {
	pkgs, loadErr := packages.Load(cfg, "./api")
	if loadErr != nil {
		fail("loading api package: %v", loadErr)
	}
	if len(pkgs) != 1 {
		fail("expected one package in api/, got %d", len(pkgs))
	}
	return pkgs[0]
}

// dropGeneratedFile removes borgo.gen.go from the analyzed syntax: its
// borgo.Handle calls would otherwise re-register every directive route as a
// manual one and collide with the directives that produced them.
func dropGeneratedFile(pkg *packages.Package) {
	kept := pkg.Syntax[:0]
	for _, file := range pkg.Syntax {
		name := filepath.Base(pkg.Fset.Position(file.Pos()).Filename)
		if name != "borgo.gen.go" {
			kept = append(kept, file)
		}
	}
	pkg.Syntax = kept
}

func hasErrorIn(pkg *packages.Package, file string) bool {
	for _, e := range pkg.Errors {
		if strings.Contains(e.Pos, file) {
			return true
		}
	}
	return false
}

// apiPackageName reads the package clause of the first real api/*.go file so
// the overlay stub and the generated mounting use the right name.
func apiPackageName(root string) string {
	entries, err := os.ReadDir(filepath.Join(root, "api"))
	if err != nil {
		fail("%v", err)
	}
	fset := token.NewFileSet()
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".go") || e.Name() == "borgo.gen.go" {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(root, "api", e.Name()), nil, parser.PackageClauseOnly)
		if err == nil {
			return f.Name.Name
		}
	}
	return "api"
}

var handlerSig = "func(http.ResponseWriter, *http.Request)"

func isHandlerSig(fn *types.Func) bool {
	sig, ok := fn.Type().(*types.Signature)
	if !ok || sig.Recv() != nil || sig.TypeParams().Len() != 0 ||
		sig.Params().Len() != 2 || sig.Results().Len() != 0 {
		return false
	}
	return sig.Params().At(0).Type().String() == "net/http.ResponseWriter" &&
		sig.Params().At(1).Type().String() == "*net/http.Request"
}

// splitPattern splits "METHOD /path" tolerantly: manual borgo.Handle patterns
// may be method-less serve-mux patterns like "/path".
func splitPattern(p string) (method, path string) {
	if i := strings.IndexByte(p, ' '); i >= 0 {
		return p[:i], p[i+1:]
	}
	return "", p
}

// collectDirectives finds every //borgo:route directive and validates it
// against the manually registered patterns.
func collectDirectives(pkg *packages.Package, decls map[*types.Func]*ast.FuncDecl, manual []route) []route {
	taken := map[string]string{}
	for _, r := range manual {
		name := "?"
		if r.handler != nil {
			name = r.handler.Name()
		}
		taken[r.pattern] = name + " (borgo.Handle)"
	}

	var out []route
	for fn, decl := range decls {
		if decl.Doc == nil {
			continue
		}
		for _, comment := range decl.Doc.List {
			m := directiveRe.FindStringSubmatch(comment.Text)
			if m == nil {
				continue
			}
			pattern := strings.TrimSpace(m[1])
			pos := pkg.Fset.Position(comment.Pos())
			if !patternRe.MatchString(pattern) {
				fail("%s: //borgo:route %q: want \"METHOD /path\" with METHOD one of GET POST PUT PATCH DELETE HEAD OPTIONS", pos, pattern)
			}
			if sig, ok := fn.Type().(*types.Signature); ok {
				if sig.Recv() != nil {
					fail("%s: //borgo:route on method %s; handlers must be package-level functions", pos, fn.Name())
				}
				if sig.TypeParams().Len() != 0 {
					fail("%s: //borgo:route on generic function %s; handlers cannot have type parameters", pos, fn.Name())
				}
			}
			if !isHandlerSig(fn) {
				fail("%s: //borgo:route on %s, which is not a %s", pos, fn.Name(), handlerSig)
			}
			if prev, dup := taken[pattern]; dup {
				fail("%s: pattern %q already registered by %s", pos, pattern, prev)
			}
			taken[pattern] = fn.Name() + " (//borgo:route)"
			out = append(out, route{pattern: pattern, handler: fn})
		}
	}
	return out
}

// warnLooseRouteComments flags comments that look like a //borgo:route
// directive but are not the doc comment of any function (space after //,
// blank line before the func): they would otherwise be ignored silently.
func warnLooseRouteComments(pkg *packages.Package, decls map[*types.Func]*ast.FuncDecl) {
	attached := map[*ast.Comment]bool{}
	for _, decl := range decls {
		if decl.Doc == nil {
			continue
		}
		for _, comment := range decl.Doc.List {
			if directiveRe.MatchString(comment.Text) {
				attached[comment] = true
			}
		}
	}
	for _, file := range pkg.Syntax {
		for _, group := range file.Comments {
			for _, comment := range group.List {
				if attached[comment] || !looseDirective.MatchString(comment.Text) {
					continue
				}
				pos := pkg.Fset.Position(comment.Pos())
				fmt.Fprintf(os.Stderr, "borgogen: warning: %s: comment looks like //borgo:route but is not attached to a handler; it was ignored\n", pos)
			}
		}
	}
}

// writeMounting generates api/borgo.gen.go registering every directive
// handler, or removes it when no directives exist.
func writeMounting(root, pkgName string, directives []route, decls map[*types.Func]*ast.FuncDecl) {
	if len(directives) == 0 {
		os.Remove(filepath.Join(root, genGoFile))
		return
	}
	sorted := append([]route(nil), directives...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].pattern < sorted[j].pattern })

	var out strings.Builder
	out.WriteString("// generated by borgogen - do not edit\npackage " + pkgName + "\n\n")
	out.WriteString("import \"" + borgoPath + "\"\n\nfunc init() {\n")
	for _, r := range sorted {
		fmt.Fprintf(&out, "\tborgo.Handle(%q, %s)\n", r.pattern, r.handler.Name())
	}
	out.WriteString("}\n")
	writeIfChanged(filepath.Join(root, genGoFile), out.String())
}

func writeIfChanged(path, content string) {
	if current, err := os.ReadFile(path); err == nil && string(current) == content {
		// still mark the output as regenerated: mtime freshness (borgo doctor)
		// must clear after a run even when the content is already right
		now := time.Now()
		os.Chtimes(path, now, now)
		return
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		fail("%v", err)
	}
}

// borgoFunc resolves a call expression's callee to a function of the borgo
// package, returning its name, or "" when it is anything else.
func borgoFunc(info *types.Info, call *ast.CallExpr) (string, *ast.Ident) {
	fun := call.Fun
	if idx, ok := fun.(*ast.IndexExpr); ok {
		// explicit type arguments, e.g. borgo.Bind[T](r)
		fun = idx.X
	}
	sel, ok := fun.(*ast.SelectorExpr)
	if !ok {
		return "", nil
	}
	fn, ok := info.Uses[sel.Sel].(*types.Func)
	if !ok || fn.Pkg() == nil || fn.Pkg().Path() != borgoPath {
		return "", nil
	}
	return fn.Name(), sel.Sel
}

func collectRoutes(pkg *packages.Package) []route {
	var routes []route
	for _, file := range pkg.Syntax {
		ast.Inspect(file, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			name, _ := borgoFunc(pkg.TypesInfo, call)
			if name != "Handle" || len(call.Args) != 2 {
				return true
			}
			tv := pkg.TypesInfo.Types[call.Args[0]]
			if tv.Value == nil || tv.Value.Kind() != constant.String {
				return true
			}
			routes = append(routes, route{
				pattern: constant.StringVal(tv.Value),
				handler: handlerFunc(pkg.TypesInfo, call.Args[1]),
			})
			return true
		})
	}
	return routes
}

func constString(pkg *packages.Package, expr ast.Expr) (string, bool) {
	tv := pkg.TypesInfo.Types[expr]
	if tv.Value == nil || tv.Value.Kind() != constant.String {
		return "", false
	}
	return constant.StringVal(tv.Value), true
}

// collectPushes gathers every borgo.PushT call into a "topic/event" -> payload
// type map; payloads pushed under the same key union like response types do.
// Topic and event must be constant strings - dynamic ones belong to borgo.Push,
// which stays out of the generated map.
func collectPushes(pkg *packages.Package, gen *tsGen) ([]string, map[string]string) {
	unions := map[string]*union{}
	var keys []string
	for _, file := range pkg.Syntax {
		ast.Inspect(file, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			name, sel := borgoFunc(pkg.TypesInfo, call)
			if name != "PushT" || len(call.Args) != 3 {
				return true
			}
			pos := pkg.Fset.Position(call.Pos())
			topic, topicOK := constString(pkg, call.Args[0])
			event, eventOK := constString(pkg, call.Args[1])
			if !topicOK || !eventOK {
				fail("%s: borgo.PushT needs constant topic and event strings; use borgo.Push for dynamic ones", pos)
			}
			if strings.Contains(topic, "/") {
				fail(`%s: borgo.PushT topic %q must not contain "/" - WsEvents keys are "topic/event", so the browser would subscribe to the wrong topic`, pos, topic)
			}
			inst, ok := pkg.TypesInfo.Instances[sel]
			if !ok || inst.TypeArgs.Len() != 1 {
				return true
			}
			key := topic + "/" + event
			if unions[key] == nil {
				unions[key] = &union{}
				keys = append(keys, key)
			}
			unions[key].add(gen.tsType(inst.TypeArgs.At(0)))
			return true
		})
	}
	sort.Strings(keys)
	entries := make(map[string]string, len(keys))
	for _, k := range keys {
		entries[k] = unions[k].String()
	}
	return keys, entries
}

func handlerFunc(info *types.Info, expr ast.Expr) *types.Func {
	switch e := expr.(type) {
	case *ast.Ident:
		if fn, ok := info.Uses[e].(*types.Func); ok {
			return fn
		}
	case *ast.SelectorExpr:
		if fn, ok := info.Uses[e.Sel].(*types.Func); ok {
			return fn
		}
	case *ast.CallExpr:
		// borgo.Authed(h) is transparent: the route keeps h's types
		if name, _ := borgoFunc(info, e); name == "Authed" && len(e.Args) == 1 {
			return handlerFunc(info, e.Args[0])
		}
	}
	return nil
}

func funcDecls(pkg *packages.Package) map[*types.Func]*ast.FuncDecl {
	decls := map[*types.Func]*ast.FuncDecl{}
	for _, file := range pkg.Syntax {
		for _, d := range file.Decls {
			if fd, ok := d.(*ast.FuncDecl); ok {
				if fn, ok := pkg.TypesInfo.Defs[fd.Name].(*types.Func); ok {
					decls[fn] = fd
				}
			}
		}
	}
	return decls
}

type tsGen struct {
	// keyed on the instantiated type string, so Page[A] and Page[B] emit
	// distinct interfaces instead of collapsing on the generic origin
	names     map[string]string
	taken     map[string]bool
	defs      []string
	apiPkg    *types.Package
	overrides map[string]string
}

// collectTypeOverrides gathers every "//borgo:type Go TS" directive. The Go
// type is "pkgpath.Name" for imported types or a bare name for api types.
func collectTypeOverrides(pkg *packages.Package) map[string]string {
	out := map[string]string{}
	for _, file := range pkg.Syntax {
		for _, group := range file.Comments {
			for _, comment := range group.List {
				m := typeRe.FindStringSubmatch(comment.Text)
				if m == nil {
					// prose like "//borgo:types are ..." is not a directive
					rest, isDirective := strings.CutPrefix(comment.Text, "//borgo:type")
					if isDirective && (rest == "" || rest[0] == ' ' || rest[0] == '\t') {
						pos := pkg.Fset.Position(comment.Pos())
						fail("%s: malformed directive, want //borgo:type <go type> <ts type>", pos)
					}
					continue
				}
				out[m[1]] = strings.TrimSpace(m[2])
			}
		}
	}
	return out
}

type union struct {
	seen  map[string]bool
	parts []string
}

func (u *union) add(ts string) {
	if u.seen == nil {
		u.seen = map[string]bool{}
	}
	if !u.seen[ts] {
		u.seen[ts] = true
		u.parts = append(u.parts, ts)
	}
}

func (u *union) String() string {
	return strings.Join(u.parts, " | ")
}

// localCallee resolves a call to a function of the api package itself, so
// borgo.JSON/WriteJSON/Bind calls inside helpers are followed.
func localCallee(pkg *packages.Package, call *ast.CallExpr) *types.Func {
	var fn *types.Func
	switch e := call.Fun.(type) {
	case *ast.Ident:
		fn, _ = pkg.TypesInfo.Uses[e].(*types.Func)
	case *ast.SelectorExpr:
		fn, _ = pkg.TypesInfo.Uses[e.Sel].(*types.Func)
	}
	if fn == nil || fn.Pkg() != pkg.Types {
		return nil
	}
	return fn
}

// bridgeTypes unions the response type (borgo.JSON[T] and borgo.WriteJSON
// calls) and the request type (borgo.Bind[T] calls) reachable from the
// handler, following calls into same-package helper functions.
func (g *tsGen) bridgeTypes(pkg *packages.Package, decls map[*types.Func]*ast.FuncDecl, decl *ast.FuncDecl) (response, request string) {
	var resp, req union
	visited := map[*ast.FuncDecl]bool{}

	var walk func(d *ast.FuncDecl)
	walk = func(d *ast.FuncDecl) {
		if d == nil || d.Body == nil || visited[d] {
			return
		}
		visited[d] = true
		ast.Inspect(d.Body, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			switch name, sel := borgoFunc(pkg.TypesInfo, call); name {
			case "JSON", "Bind", "BindMax":
				if inst, ok := pkg.TypesInfo.Instances[sel]; ok && inst.TypeArgs.Len() == 1 {
					ts := g.tsType(inst.TypeArgs.At(0))
					if name == "JSON" {
						resp.add(ts)
					} else {
						req.add(ts)
					}
				}
			case "WriteJSON":
				if len(call.Args) == 3 {
					if tv := pkg.TypesInfo.Types[call.Args[2]]; tv.Type != nil {
						resp.add(g.tsType(types.Default(tv.Type)))
					}
				}
			case "":
				if fn := localCallee(pkg, call); fn != nil {
					walk(decls[fn])
				}
			}
			return true
		})
	}
	walk(decl)

	if len(resp.parts) == 0 {
		return "unknown", req.String()
	}
	return resp.String(), req.String()
}

func hasCustomMarshal(t types.Type) bool {
	for _, T := range []types.Type{t, types.NewPointer(t)} {
		if m, _, _ := types.LookupFieldOrMethod(T, true, nil, "MarshalJSON"); m != nil {
			return true
		}
	}
	return false
}

func (g *tsGen) tsType(t types.Type) string {
	switch t := t.(type) {
	case *types.Named:
		obj := t.Obj()
		if ts, ok := g.override(obj); ok {
			return ts
		}
		if obj.Pkg() != nil && obj.Pkg().Path() == "time" && obj.Name() == "Time" {
			return "string"
		}
		if hasCustomMarshal(t) {
			return "unknown"
		}
		if s, ok := t.Underlying().(*types.Struct); ok {
			return g.interfaceFor(t, s)
		}
		return g.tsType(t.Underlying())
	case *types.Alias:
		return g.tsType(types.Unalias(t))
	case *types.Basic:
		switch {
		case t.Info()&types.IsBoolean != 0:
			return "boolean"
		case t.Info()&types.IsNumeric != 0:
			return "number"
		case t.Info()&types.IsString != 0:
			return "string"
		}
		return "unknown"
	case *types.Pointer:
		return g.tsType(t.Elem()) + " | null"
	case *types.Slice:
		if b, ok := t.Elem().(*types.Basic); ok && b.Kind() == types.Byte {
			return "string"
		}
		return "Array<" + g.tsType(t.Elem()) + ">"
	case *types.Array:
		return "Array<" + g.tsType(t.Elem()) + ">"
	case *types.Map:
		if b, ok := t.Key().Underlying().(*types.Basic); ok && b.Info()&(types.IsString|types.IsNumeric) != 0 {
			return "Record<string, " + g.tsType(t.Elem()) + ">"
		}
		return "unknown"
	case *types.Struct:
		return "{ " + strings.Join(g.fields(t), "; ") + " }"
	}
	return "unknown"
}

func (g *tsGen) override(obj *types.TypeName) (string, bool) {
	if obj.Pkg() != nil {
		if ts, ok := g.overrides[obj.Pkg().Path()+"."+obj.Name()]; ok {
			return ts, true
		}
	}
	if obj.Pkg() == nil || obj.Pkg() == g.apiPkg {
		if ts, ok := g.overrides[obj.Name()]; ok {
			return ts, true
		}
	}
	return "", false
}

// typeArgSuffix mangles instantiated type arguments into a readable,
// deterministic name part: Page[Widget] -> "Widget", Page[[]post.Item] ->
// "PostItem".
func (g *tsGen) typeArgSuffix(args *types.TypeList) string {
	if args == nil || args.Len() == 0 {
		return ""
	}
	var b strings.Builder
	for i := 0; i < args.Len(); i++ {
		s := types.TypeString(args.At(i), func(p *types.Package) string {
			if p == g.apiPkg {
				return ""
			}
			return p.Name()
		})
		up := true
		for _, r := range s {
			if r == '_' || unicode.IsLetter(r) || unicode.IsDigit(r) {
				if up {
					r = unicode.ToUpper(r)
					up = false
				}
				b.WriteRune(r)
			} else {
				up = true
			}
		}
	}
	return b.String()
}

func (g *tsGen) interfaceFor(t *types.Named, s *types.Struct) string {
	key := types.TypeString(t, nil)
	if name, ok := g.names[key]; ok {
		return name
	}
	obj := t.Obj()
	name := obj.Name() + g.typeArgSuffix(t.TypeArgs())
	if g.taken[name] && obj.Pkg() != nil {
		pkgName := obj.Pkg().Name()
		name = strings.ToUpper(pkgName[:1]) + pkgName[1:] + name
	}
	base := name
	for i := 2; g.taken[name]; i++ {
		name = fmt.Sprintf("%s%d", base, i)
	}
	g.taken[name] = true
	g.names[key] = name

	fields := g.fields(s)
	g.defs = append(g.defs, "export interface "+name+" {\n  "+strings.Join(fields, ";\n  ")+";\n}\n")
	return name
}

// fields follows encoding/json: exported fields only, json tags for naming,
// omitempty marks the field optional, embedded structs are flattened.
func (g *tsGen) fields(s *types.Struct) []string {
	var out []string
	for i := 0; i < s.NumFields(); i++ {
		f := s.Field(i)
		if !f.Exported() {
			continue
		}
		name, opts := parseJSONTag(s.Tag(i))
		if name == "-" {
			continue
		}
		if f.Embedded() && name == "" {
			et := f.Type()
			if p, ok := et.(*types.Pointer); ok {
				et = p.Elem()
			}
			if named, ok := et.(*types.Named); ok && !hasCustomMarshal(named) {
				if es, ok := named.Underlying().(*types.Struct); ok {
					out = append(out, g.fields(es)...)
					continue
				}
			}
		}
		if name == "" {
			name = f.Name()
		}
		optional := ""
		if strings.Contains(opts, "omitempty") {
			optional = "?"
		}
		ts := g.tsType(f.Type())
		if strings.Contains(opts, "string") && ts == "number" {
			ts = "string"
		}
		out = append(out, fmt.Sprintf("%s%s: %s", name, optional, ts))
	}
	if len(out) == 0 {
		return []string{"[key: string]: unknown"}
	}
	return out
}

func parseJSONTag(tag string) (name, opts string) {
	value, ok := lookupTag(tag, "json")
	if !ok {
		return "", ""
	}
	if i := strings.Index(value, ","); i >= 0 {
		return value[:i], value[i+1:]
	}
	return value, ""
}

func lookupTag(tag, key string) (string, bool) {
	// minimal reflect.StructTag.Lookup
	for tag != "" {
		i := 0
		for i < len(tag) && tag[i] == ' ' {
			i++
		}
		tag = tag[i:]
		if tag == "" {
			break
		}
		i = 0
		for i < len(tag) && tag[i] > ' ' && tag[i] != ':' && tag[i] != '"' {
			i++
		}
		if i == 0 || i+1 >= len(tag) || tag[i] != ':' || tag[i+1] != '"' {
			break
		}
		k := tag[:i]
		tag = tag[i+1:]
		i = 1
		for i < len(tag) && tag[i] != '"' {
			if tag[i] == '\\' {
				i++
			}
			i++
		}
		if i >= len(tag) {
			break
		}
		value := tag[1:i]
		tag = tag[i+1:]
		if k == key {
			return value, true
		}
	}
	return "", false
}
