// Command borgogen statically analyzes an app's api/ package and generates
// .borgo/api-types.d.ts, mapping every registered route pattern to the
// TypeScript shape of its response. A route's response type is the union of
// the T in every borgo.JSON[T] call made directly in its handler's body.
package main

import (
	"fmt"
	"go/ast"
	"go/constant"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"golang.org/x/tools/go/packages"
)

const borgoPath = "github.com/LuigiDavideMicca/borgo"

type route struct {
	pattern string
	handler *types.Func
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "borgogen: "+format+"\n", args...)
	os.Exit(1)
}

func main() {
	if _, err := os.Stat("api"); err != nil {
		fail("no api/ directory here; run borgogen from the app root")
	}

	cfg := &packages.Config{
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedSyntax |
			packages.NeedTypes | packages.NeedTypesInfo | packages.NeedDeps | packages.NeedImports,
	}
	pkgs, err := packages.Load(cfg, "./api")
	if err != nil {
		fail("loading api package: %v", err)
	}
	if len(pkgs) != 1 {
		fail("expected one package in api/, got %d", len(pkgs))
	}
	pkg := pkgs[0]
	for _, e := range pkg.Errors {
		fmt.Fprintln(os.Stderr, "borgogen: "+e.Error())
	}
	if len(pkg.Errors) > 0 {
		os.Exit(1)
	}

	routes := collectRoutes(pkg)
	decls := funcDecls(pkg)

	gen := &tsGen{names: map[*types.TypeName]string{}, taken: map[string]bool{}}
	entries := make(map[string]string, len(routes))
	for _, r := range routes {
		entries[r.pattern] = gen.responseType(pkg, decls[r.handler])
	}

	patterns := make([]string, 0, len(entries))
	for p := range entries {
		patterns = append(patterns, p)
	}
	sort.Slice(patterns, func(i, j int) bool {
		a, b := strings.SplitN(patterns[i], " ", 2), strings.SplitN(patterns[j], " ", 2)
		if a[1] != b[1] {
			return a[1] < b[1]
		}
		return a[0] < b[0]
	})

	var out strings.Builder
	out.WriteString("// generated by borgogen - do not edit\n\n")
	for _, def := range gen.defs {
		out.WriteString(def)
		out.WriteString("\n")
	}
	out.WriteString("declare module \"borgo\" {\n  interface ApiRoutes {\n")
	for _, p := range patterns {
		fmt.Fprintf(&out, "    %q: %s;\n", p, entries[p])
	}
	out.WriteString("  }\n}\n\nexport {};\n")

	if err := os.MkdirAll(".borgo", 0o755); err != nil {
		fail("%v", err)
	}
	writeIfChanged(filepath.Join(".borgo", "api-types.d.ts"), out.String())
	fmt.Printf("borgogen: %d routes -> .borgo/api-types.d.ts\n", len(patterns))
}

func writeIfChanged(path, content string) {
	if current, err := os.ReadFile(path); err == nil && string(current) == content {
		return
	}
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		fail("%v", err)
	}
}

// borgoFunc resolves a call expression's callee to a function of the borgo
// package, returning its name, or "" when it is anything else.
func borgoFunc(info *types.Info, call *ast.CallExpr) (string, *ast.Ident) {
	sel, ok := call.Fun.(*ast.SelectorExpr)
	if !ok {
		return "", nil
	}
	fn, ok := info.Uses[sel.Sel].(*types.Func)
	if !ok || fn.Pkg() == nil || fn.Pkg().Path() != borgoPath {
		return "", nil
	}
	return fn.Name(), sel.Sel
}

func collectRoutes(pkg *packages.Package) []route {
	var routes []route
	for _, file := range pkg.Syntax {
		ast.Inspect(file, func(n ast.Node) bool {
			call, ok := n.(*ast.CallExpr)
			if !ok {
				return true
			}
			name, _ := borgoFunc(pkg.TypesInfo, call)
			if name != "Handle" || len(call.Args) != 2 {
				return true
			}
			tv := pkg.TypesInfo.Types[call.Args[0]]
			if tv.Value == nil || tv.Value.Kind() != constant.String {
				return true
			}
			routes = append(routes, route{
				pattern: constant.StringVal(tv.Value),
				handler: handlerFunc(pkg.TypesInfo, call.Args[1]),
			})
			return true
		})
	}
	return routes
}

func handlerFunc(info *types.Info, expr ast.Expr) *types.Func {
	switch e := expr.(type) {
	case *ast.Ident:
		if fn, ok := info.Uses[e].(*types.Func); ok {
			return fn
		}
	case *ast.SelectorExpr:
		if fn, ok := info.Uses[e.Sel].(*types.Func); ok {
			return fn
		}
	}
	return nil
}

func funcDecls(pkg *packages.Package) map[*types.Func]*ast.FuncDecl {
	decls := map[*types.Func]*ast.FuncDecl{}
	for _, file := range pkg.Syntax {
		for _, d := range file.Decls {
			if fd, ok := d.(*ast.FuncDecl); ok {
				if fn, ok := pkg.TypesInfo.Defs[fd.Name].(*types.Func); ok {
					decls[fn] = fd
				}
			}
		}
	}
	return decls
}

type tsGen struct {
	names map[*types.TypeName]string
	taken map[string]bool
	defs  []string
}

// responseType unions the T of every borgo.JSON[T] call in the handler body.
func (g *tsGen) responseType(pkg *packages.Package, decl *ast.FuncDecl) string {
	if decl == nil || decl.Body == nil {
		return "unknown"
	}
	seen := map[string]bool{}
	var parts []string
	ast.Inspect(decl.Body, func(n ast.Node) bool {
		call, ok := n.(*ast.CallExpr)
		if !ok {
			return true
		}
		name, sel := borgoFunc(pkg.TypesInfo, call)
		if name != "JSON" {
			return true
		}
		inst, ok := pkg.TypesInfo.Instances[sel]
		if !ok || inst.TypeArgs.Len() != 1 {
			return true
		}
		ts := g.tsType(inst.TypeArgs.At(0))
		if !seen[ts] {
			seen[ts] = true
			parts = append(parts, ts)
		}
		return true
	})
	if len(parts) == 0 {
		return "unknown"
	}
	return strings.Join(parts, " | ")
}

func hasCustomMarshal(t types.Type) bool {
	for _, T := range []types.Type{t, types.NewPointer(t)} {
		if m, _, _ := types.LookupFieldOrMethod(T, true, nil, "MarshalJSON"); m != nil {
			return true
		}
	}
	return false
}

func (g *tsGen) tsType(t types.Type) string {
	switch t := t.(type) {
	case *types.Named:
		obj := t.Obj()
		if obj.Pkg() != nil && obj.Pkg().Path() == "time" && obj.Name() == "Time" {
			return "string"
		}
		if hasCustomMarshal(t) {
			return "unknown"
		}
		if s, ok := t.Underlying().(*types.Struct); ok {
			return g.interfaceFor(obj, s)
		}
		return g.tsType(t.Underlying())
	case *types.Alias:
		return g.tsType(types.Unalias(t))
	case *types.Basic:
		switch {
		case t.Info()&types.IsBoolean != 0:
			return "boolean"
		case t.Info()&types.IsNumeric != 0:
			return "number"
		case t.Info()&types.IsString != 0:
			return "string"
		}
		return "unknown"
	case *types.Pointer:
		return g.tsType(t.Elem()) + " | null"
	case *types.Slice:
		if b, ok := t.Elem().(*types.Basic); ok && b.Kind() == types.Byte {
			return "string"
		}
		return "Array<" + g.tsType(t.Elem()) + ">"
	case *types.Array:
		return "Array<" + g.tsType(t.Elem()) + ">"
	case *types.Map:
		if b, ok := t.Key().Underlying().(*types.Basic); ok && b.Info()&(types.IsString|types.IsNumeric) != 0 {
			return "Record<string, " + g.tsType(t.Elem()) + ">"
		}
		return "unknown"
	case *types.Struct:
		return "{ " + strings.Join(g.fields(t), "; ") + " }"
	}
	return "unknown"
}

func (g *tsGen) interfaceFor(obj *types.TypeName, s *types.Struct) string {
	if name, ok := g.names[obj]; ok {
		return name
	}
	name := obj.Name()
	if g.taken[name] && obj.Pkg() != nil {
		pkgName := obj.Pkg().Name()
		name = strings.ToUpper(pkgName[:1]) + pkgName[1:] + name
	}
	for i := 2; g.taken[name]; i++ {
		name = fmt.Sprintf("%s%d", obj.Name(), i)
	}
	g.taken[name] = true
	g.names[obj] = name

	fields := g.fields(s)
	g.defs = append(g.defs, "export interface "+name+" {\n  "+strings.Join(fields, ";\n  ")+";\n}\n")
	return name
}

// fields follows encoding/json: exported fields only, json tags for naming,
// omitempty marks the field optional, embedded structs are flattened.
func (g *tsGen) fields(s *types.Struct) []string {
	var out []string
	for i := 0; i < s.NumFields(); i++ {
		f := s.Field(i)
		if !f.Exported() {
			continue
		}
		name, opts := parseJSONTag(s.Tag(i))
		if name == "-" {
			continue
		}
		if f.Embedded() && name == "" {
			et := f.Type()
			if p, ok := et.(*types.Pointer); ok {
				et = p.Elem()
			}
			if named, ok := et.(*types.Named); ok && !hasCustomMarshal(named) {
				if es, ok := named.Underlying().(*types.Struct); ok {
					out = append(out, g.fields(es)...)
					continue
				}
			}
		}
		if name == "" {
			name = f.Name()
		}
		optional := ""
		if strings.Contains(opts, "omitempty") {
			optional = "?"
		}
		ts := g.tsType(f.Type())
		if strings.Contains(opts, "string") && ts == "number" {
			ts = "string"
		}
		out = append(out, fmt.Sprintf("%s%s: %s", name, optional, ts))
	}
	if len(out) == 0 {
		return []string{"[key: string]: unknown"}
	}
	return out
}

func parseJSONTag(tag string) (name, opts string) {
	value, ok := lookupTag(tag, "json")
	if !ok {
		return "", ""
	}
	if i := strings.Index(value, ","); i >= 0 {
		return value[:i], value[i+1:]
	}
	return value, ""
}

func lookupTag(tag, key string) (string, bool) {
	// minimal reflect.StructTag.Lookup
	for tag != "" {
		i := 0
		for i < len(tag) && tag[i] == ' ' {
			i++
		}
		tag = tag[i:]
		if tag == "" {
			break
		}
		i = 0
		for i < len(tag) && tag[i] > ' ' && tag[i] != ':' && tag[i] != '"' {
			i++
		}
		if i == 0 || i+1 >= len(tag) || tag[i] != ':' || tag[i+1] != '"' {
			break
		}
		k := tag[:i]
		tag = tag[i+1:]
		i = 1
		for i < len(tag) && tag[i] != '"' {
			if tag[i] == '\\' {
				i++
			}
			i++
		}
		if i >= len(tag) {
			break
		}
		value := tag[1:i]
		tag = tag[i+1:]
		if k == key {
			return value, true
		}
	}
	return "", false
}
