// generated by borgogen - do not edit

export interface Row {
  "user-name": string;
  "a.b": string;
  "1st": string;
  città: string;
  plain_$1: string;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/rows": { response: Row };
  }
}

export {};
