// generated by borgogen - do not edit

export interface Dashes {
  "-": number;
  keep: number;
}

export interface Quoted {
  b: string;
  i: string;
  f: string;
  st: string;
  p: string | null;
}

export interface Row {
  "user-name": string;
  "a.b": string;
  "1st": string;
  città: string;
  plain_$1: string;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/dashes": { response: Dashes };
    "GET /api/quoted": { response: Quoted };
    "GET /api/rows": { response: Row };
  }
}

export {};
