// generated by borgogen - do not edit

export interface ApiArray {
  l: Array<number>;
}

export interface ApiRecord {
  m: Record<string, number>;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/arr": { response: ApiArray };
    "GET /api/rec": { response: ApiRecord };
  }
}

export {};
