// generated by borgogen - do not edit

export interface Post {
  title: string;
}

export interface PagePost {
  items: Array<Post>;
  total: number;
}

export interface Widget {
  name: string;
}

export interface PageWidget {
  items: Array<Widget>;
  total: number;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/posts": { response: PagePost };
    "GET /api/widgets": { response: PageWidget };
  }
}

export {};
