import { Glob } from "bun";
import { filePathToPattern } from "./router";

const outDir = "public/assets";
const manifestPath = "framework/routes.gen.tsx";

const dynamicSegments = (pattern: string) =>
  pattern.split("/").filter((s) => s.startsWith(":")).length;

export async function generateManifest() {
  const files = [...new Glob("**/*.tsx").scanSync("pages")]
    .map((f) => f.replaceAll("\\", "/"))
    .sort();

  // static segments win over dynamic ones
  const pages = files
    .map((file) => ({ file, pattern: filePathToPattern(file) }))
    .sort(
      (a, b) =>
        dynamicSegments(a.pattern) - dynamicSegments(b.pattern) ||
        a.pattern.localeCompare(b.pattern),
    );

  const src = [
    "// generated by framework/build.ts - do not edit",
    'import type { Route } from "./router";',
    ...pages.map((p, i) => `import * as page${i} from "../pages/${p.file.replace(/\.tsx$/, "")}";`),
    "",
    "export const routes: Route[] = [",
    ...pages.map((p, i) => `  { pattern: ${JSON.stringify(p.pattern)}, module: page${i} },`),
    "];",
    "",
  ].join("\n");

  const file = Bun.file(manifestPath);
  const current = (await file.exists()) ? await file.text() : "";
  if (current !== src) await Bun.write(manifestPath, src);
}

export async function buildAssets(dev = false) {
  await generateManifest();

  const sass = await import("sass");
  const css = sass.compile("style.scss", { style: dev ? "expanded" : "compressed" });
  await Bun.write(`${outDir}/style.css`, css.css);

  await Bun.build({
    entrypoints: ["framework/client.tsx"],
    outdir: outDir,
    minify: !dev,
  });
}

if (import.meta.main) {
  await buildAssets();

  const bin = "dist/api" + (process.platform === "win32" ? ".exe" : "");
  const goBuild = Bun.spawn(["go", "build", "-o", bin, "."], {
    stdout: "inherit",
    stderr: "inherit",
  });
  if ((await goBuild.exited) !== 0) process.exit(1);

  console.log(`client assets in ${outDir}, api binary at ${bin}`);
}
