// generated by borgogen - do not edit

export interface Resp {
  id: string;
  lvl: string;
  addr: string;
  keyed: Record<string, number>;
  plain: number;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/resp": { response: Resp };
  }
}

export {};
