import { Glob } from "bun";
import { existsSync } from "node:fs";
import { filePathToPattern } from "./router";

const outDir = "public/assets";
const genDir = ".borgo";

const dynamicSegments = (pattern: string) =>
  pattern.split("/").filter((s) => s.startsWith(":")).length;

async function writeIfChanged(path: string, content: string) {
  const file = Bun.file(path);
  const current = (await file.exists()) ? await file.text() : "";
  if (current !== content) await Bun.write(path, content);
}

export async function generateManifest() {
  const files = [...new Glob("**/*.tsx").scanSync("pages")]
    .map((f) => f.replaceAll("\\", "/"))
    .sort();

  // static segments win over dynamic ones
  const pages = files
    .map((file) => ({ file, pattern: filePathToPattern(file) }))
    .sort(
      (a, b) =>
        dynamicSegments(a.pattern) - dynamicSegments(b.pattern) ||
        a.pattern.localeCompare(b.pattern),
    );

  const manifest = [
    "// generated by borgo - do not edit",
    'import type { Route } from "borgo/router";',
    ...pages.map((p, i) => `import * as page${i} from "../pages/${p.file.replace(/\.tsx$/, "")}";`),
    "",
    "export const routes: Route[] = [",
    ...pages.map((p, i) => `  { pattern: ${JSON.stringify(p.pattern)}, module: page${i} },`),
    "];",
    "",
  ].join("\n");
  await writeIfChanged(`${genDir}/routes.gen.tsx`, manifest);

  // react is imported here, from inside the app, so the bundle never picks up
  // a second copy through a linked borgo checkout
  const entry = [
    "// generated by borgo - do not edit",
    'import { createElement } from "react";',
    'import { hydrateRoot } from "react-dom/client";',
    'import { matchRoute } from "borgo/router";',
    'import { routes } from "./routes.gen";',
    "",
    "const matched = matchRoute(location.pathname, routes);",
    "if (matched) {",
    "  hydrateRoot(",
    '    document.getElementById("root")!,',
    "    createElement(matched.route.module.default, (window as any).__PROPS__ ?? {}),",
    "  );",
    "}",
    "",
  ].join("\n");
  await writeIfChanged(`${genDir}/client.tsx`, entry);
}

export async function buildAssets(dev = false) {
  await generateManifest();

  if (existsSync("style.scss")) {
    const sass = await import("sass");
    const css = sass.compile("style.scss", { style: dev ? "expanded" : "compressed" });
    await Bun.write(`${outDir}/style.css`, css.css);
  }

  await Bun.build({
    entrypoints: [`${genDir}/client.tsx`],
    outdir: outDir,
    minify: !dev,
  });
}
