import { Glob } from "bun";
import { existsSync, readdirSync, rmSync } from "node:fs";
import { join, sep } from "node:path";
import { filePathToPattern } from "./router";

const outDir = "public/assets";
const genDir = ".borgo";

const dynamicSegments = (pattern: string) =>
  pattern.split("/").filter((s) => s.startsWith(":")).length;

async function writeIfChanged(path: string, content: string) {
  const file = Bun.file(path);
  const current = (await file.exists()) ? await file.text() : "";
  if (current !== content) await Bun.write(path, content);
}

// the hydrate export must be a literal so it can be read without executing the page
const hydrateRe = /export\s+const\s+hydrate\s*(?::[^=]+)?=\s*(false|true|["']visible["'])/;

function parseHydrate(source: string): "false" | "true" | '"visible"' {
  const match = source.match(hydrateRe);
  if (!match) return "true";
  return match[1] === "false" ? "false" : match[1] === "true" ? "true" : '"visible"';
}

// islands are detected by the <Island marker in the page (or layout) source,
// like hydrate: read statically, without executing the page
const islandRe = /<Island[\s/>]/;

export async function generateManifest() {
  const files = [...new Glob("**/*.tsx").scanSync("pages")]
    .map((f) => f.replaceAll("\\", "/"))
    .sort();

  const special = (f: string) => f.split("/").pop()!.startsWith("_");

  const sources = new Map<string, string>();
  for (const f of files) sources.set(f, await Bun.file(`pages/${f}`).text());

  const layoutDirs = files
    .filter((f) => f.endsWith("_layout.tsx"))
    .map((f) => f.slice(0, -"_layout.tsx".length).replace(/\/$/, ""));

  // layout chain for a page, outermost first
  const layoutsFor = (file: string) => {
    const parts = file.split("/").slice(0, -1);
    const chain: string[] = [];
    for (let i = 0; i <= parts.length; i++) {
      const dir = parts.slice(0, i).join("/");
      if (layoutDirs.includes(dir)) chain.push(dir);
    }
    return chain;
  };

  // static segments win over dynamic ones
  const pages = files
    .filter((f) => !special(f))
    .map((file) => ({ file, pattern: filePathToPattern(file) }))
    .sort(
      (a, b) =>
        dynamicSegments(a.pattern) - dynamicSegments(b.pattern) ||
        a.pattern.localeCompare(b.pattern),
    );

  const layoutName = (dir: string) => `layout${layoutDirs.indexOf(dir)}`;
  const chainFor = (file: string) => layoutsFor(file).map(layoutName).join(", ");
  const layoutImports = layoutDirs.map(
    (dir) => `import * as ${layoutName(dir)} from "../pages/${dir ? dir + "/" : ""}_layout";`,
  );

  const usesIslands = (file: string) =>
    islandRe.test(sources.get(file) ?? "") ||
    layoutsFor(file).some((dir) =>
      islandRe.test(sources.get(dir ? `${dir}/_layout.tsx` : "_layout.tsx") ?? ""),
    );

  const specialRoute = (file: string, name: string) =>
    files.includes(file)
      ? `export const ${name}: Route | null = { pattern: "*", file: ${JSON.stringify(file)}, module: ${name}Page, layouts: [${chainFor(file)}], islands: ${usesIslands(file)} };`
      : `export const ${name}: Route | null = null;`;

  const manifest = [
    "// generated by borgo - do not edit",
    'import type { Route } from "borgo/router";',
    ...layoutImports,
    ...pages.map((p, i) => `import * as page${i} from "../pages/${p.file.replace(/\.tsx$/, "")}";`),
    ...(files.includes("_404.tsx") ? ['import * as notFoundPage from "../pages/_404";'] : []),
    ...(files.includes("_500.tsx") ? ['import * as serverErrorPage from "../pages/_500";'] : []),
    "",
    "export const routes: Route[] = [",
    ...pages.map(
      (p, i) =>
        `  { pattern: ${JSON.stringify(p.pattern)}, file: ${JSON.stringify(p.file)}, module: page${i}, layouts: [${chainFor(p.file)}], islands: ${usesIslands(p.file)} },`,
    ),
    "];",
    specialRoute("_404.tsx", "notFound"),
    specialRoute("_500.tsx", "serverError"),
    "",
  ].join("\n");
  await writeIfChanged(`${genDir}/routes.gen.tsx`, manifest);

  // client manifest: pages become lazy chunks; hydrate=false pages ship no js at all
  const hydrateOf = new Map<string, string>();
  for (const p of pages) hydrateOf.set(p.file, parseHydrate(sources.get(p.file)!));
  if (files.includes("_404.tsx")) hydrateOf.set("_404.tsx", parseHydrate(sources.get("_404.tsx")!));

  const clientEntry = (pattern: string, file: string) => {
    const importPath = `../pages/${file.replace(/\.tsx$/, "")}`;
    return `{ pattern: ${JSON.stringify(pattern)}, file: ${JSON.stringify(file)}, hydrate: ${hydrateOf.get(file)}, load: () => import(${JSON.stringify(importPath)}), layouts: [${chainFor(file)}] }`;
  };

  const clientPages = pages.filter((p) => hydrateOf.get(p.file) !== "false");
  const clientManifest = [
    "// generated by borgo - do not edit",
    'import type { ClientRoute } from "borgo/runtime";',
    ...layoutImports,
    "",
    "export const routes: ClientRoute[] = [",
    ...clientPages.map((p) => `  ${clientEntry(p.pattern, p.file)},`),
    "];",
    files.includes("_404.tsx") && hydrateOf.get("_404.tsx") !== "false"
      ? `export const notFound: ClientRoute | null = ${clientEntry("*", "_404.tsx")};`
      : "export const notFound: ClientRoute | null = null;",
    "",
  ].join("\n");
  await writeIfChanged(`${genDir}/client-routes.gen.ts`, clientManifest);

  // islands: components in islands/*.tsx, registered eagerly - island code
  // rides with the entry, client="visible" defers the hydration work only
  const islandFiles = existsSync("islands")
    ? [...new Glob("*.tsx").scanSync("islands")].sort()
    : [];
  const islandsManifest = [
    "// generated by borgo - do not edit",
    'import type { ComponentType } from "react";',
    ...islandFiles.map((f, i) => `import island${i} from "../islands/${f.replace(/\.tsx$/, "")}";`),
    "",
    "export const islands: Record<string, ComponentType<any>> = {",
    ...islandFiles.map((f, i) => `  ${JSON.stringify(f.replace(/\.tsx$/, ""))}: island${i},`),
    "};",
    "",
  ].join("\n");
  await writeIfChanged(`${genDir}/islands.gen.ts`, islandsManifest);

  // react is imported here, from inside the app, and handed to the runtime so
  // the bundle never picks up a second copy through a linked borgo checkout
  const entry = [
    "// generated by borgo - do not edit",
    'import { createElement } from "react";',
    'import { hydrateRoot } from "react-dom/client";',
    'import { registerIslands } from "borgo";',
    'import { mount } from "borgo/runtime";',
    'import { routes, notFound } from "./client-routes.gen";',
    'import { islands } from "./islands.gen";',
    "",
    "registerIslands(islands, createElement);",
    "mount({ createElement, hydrateRoot, routes, notFound });",
    "",
  ].join("\n");
  await writeIfChanged(`${genDir}/client.tsx`, entry);

  // a second, tiny entry for hydrate=false pages that use islands: it
  // hydrates only the island markers, nothing else
  const islandsEntry = [
    "// generated by borgo - do not edit",
    'import { createElement } from "react";',
    'import { hydrateRoot } from "react-dom/client";',
    'import { registerIslands } from "borgo";',
    'import { mountIslands } from "borgo/runtime";',
    'import { islands } from "./islands.gen";',
    "",
    "registerIslands(islands, createElement);",
    "mountIslands({ createElement, hydrateRoot, islands });",
    "",
  ].join("\n");
  await writeIfChanged(`${genDir}/islands-client.tsx`, islandsEntry);

  return { hasIslands: islandFiles.length > 0 };
}

export type Asset = { path: string; kind: "entry-point" | "chunk" | string; size: number };

export async function buildAssets(dev = false): Promise<Asset[]> {
  const { hasIslands } = await generateManifest();

  if (existsSync("style.scss")) {
    const sass = await import("sass");
    const css = sass.compile("style.scss", { style: dev ? "expanded" : "compressed" });
    await Bun.write(`${outDir}/style.css`, css.css);
  }

  // hashed chunk names change between builds; drop the stale ones
  if (existsSync(outDir)) {
    for (const f of readdirSync(outDir)) {
      if (f.endsWith(".js")) rmSync(`${outDir}/${f}`);
    }
  }

  const define = { "process.env.NODE_ENV": JSON.stringify(dev ? "development" : "production") };
  const result = await Bun.build({
    entrypoints: [
      `${genDir}/client.tsx`,
      ...(hasIslands ? [`${genDir}/islands-client.tsx`] : []),
    ],
    outdir: outDir,
    splitting: true,
    minify: !dev,
    naming: { entry: "[name].[ext]", chunk: "[name]-[hash].[ext]" },
    define,
    plugins: [stripServerExports(define)],
  });
  return result.outputs.map((o) => ({ path: o.path, kind: o.kind, size: o.size }));
}

// pages are rewritten for the client build with their loader and action
// eliminated, so server-only code and its imports never reach the browser
function stripServerExports(define: Record<string, string>): import("bun").BunPlugin {
  const pagesDir = join(process.cwd(), "pages") + sep;
  const transpiler = new Bun.Transpiler({
    loader: "tsx",
    exports: { eliminate: ["loader", "action"] },
    trimUnusedImports: true,
    treeShaking: true,
    autoImportJSX: true,
    define,
  });
  return {
    name: "borgo-strip-server-exports",
    setup(build) {
      build.onLoad({ filter: /[\\/]pages[\\/].*\.tsx$/ }, async (args) => {
        if (!args.path.startsWith(pagesDir)) return undefined;
        const source = await Bun.file(args.path).text();
        return { contents: transpiler.transformSync(source), loader: "js" };
      });
    },
  };
}
