// borgo deploy init <target>: writes the deploy guide's blessed config for
// caddy, nginx, systemd or compose into the project, templated with the
// app's name and ports. never overwrites without --force.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { banner, c, g } from "./colors";

export type DeployContext = {
  name: string;
  port: string;
  apiPort: string;
};

export function caddyfile({ name, port }: DeployContext): string {
  return [
    `# ${name}: generated by borgo deploy init - replace example.com with your domain.`,
    "# borgo compresses responses itself, so no encode directive here.",
    "example.com {",
    `    reverse_proxy localhost:${port}`,
    "}",
    "",
  ].join("\n");
}

export function nginxConf({ name, port }: DeployContext): string {
  return [
    `# ${name}: generated by borgo deploy init - replace example.com with your domain`,
    "# and point ssl_certificate at your certs (or listen 80 behind another terminator).",
    "# upgrade headers keep websockets alive, proxy_buffering off keeps sse streaming,",
    "# and borgo compresses responses itself (gzip off is nginx's default).",
    "server {",
    "    listen 443 ssl;",
    "    server_name example.com;",
    "",
    "    location / {",
    `        proxy_pass http://localhost:${port};`,
    "        proxy_http_version 1.1;",
    "        proxy_set_header Upgrade $http_upgrade;",
    '        proxy_set_header Connection "upgrade";',
    "        proxy_set_header Host $host;",
    "        proxy_buffering off;",
    "        proxy_read_timeout 1h;",
    "    }",
    "}",
    "",
  ].join("\n");
}

export function systemdUnit({ name, port, apiPort }: DeployContext): string {
  return [
    "[Unit]",
    `Description=${name} (borgo app)`,
    "After=network.target",
    "",
    "[Service]",
    `WorkingDirectory=/srv/${name}`,
    "ExecStart=/usr/local/bin/bun run start",
    "Environment=NODE_ENV=production",
    `Environment=PORT=${port}`,
    `Environment=API_PORT=${apiPort}`,
    "Environment=SESSION_SECRET=change-me",
    "Restart=on-failure",
    "User=www-data",
    "",
    "[Install]",
    "WantedBy=multi-user.target",
    "",
  ].join("\n");
}

export function composeYml({ port }: DeployContext): string {
  return [
    "services:",
    "  app:",
    "    build: .",
    "    ports:",
    `      - "${port}:${port}"`,
    "    environment:",
    "      # SESSION_SECRET: use-a-long-random-string",
    "      # DB_PATH: /data/app.db",
    "      NODE_ENV: production",
    `      PORT: "${port}"`,
    "    volumes:",
    "      - data:/data",
    "    restart: unless-stopped",
    "",
    "volumes:",
    "  data:",
    "",
  ].join("\n");
}

export const targets: Record<string, { file: string; render: (ctx: DeployContext) => string; next: (ctx: DeployContext) => string }> = {
  caddy: {
    file: "Caddyfile",
    render: caddyfile,
    next: () => "set your domain, then: caddy run --config Caddyfile",
  },
  nginx: {
    file: "site.conf",
    render: nginxConf,
    next: ({ name }) => `set your domain and certs, then link it: /etc/nginx/sites-enabled/${name}.conf`,
  },
  systemd: {
    file: "borgo.service",
    render: systemdUnit,
    next: ({ name }) =>
      `copy to /etc/systemd/system/${name}.service, then: systemctl enable --now ${name}`,
  },
  compose: {
    file: "docker-compose.yml",
    render: composeYml,
    next: () => "docker compose up -d",
  },
};

export function projectContext(dir = "."): DeployContext {
  let name = "borgo-app";
  try {
    const pkg = JSON.parse(readFileSync(join(dir, "package.json"), "utf8")) as { name?: string };
    if (pkg.name) name = pkg.name.replace(/[^a-zA-Z0-9._-]+/g, "-").replace(/^-+|-+$/g, "") || name;
  } catch {}
  return {
    name,
    port: process.env.PORT || "3000",
    apiPort: process.env.API_PORT || "3501",
  };
}

export function deployInit(target: string | undefined, force = false, dir = "."): number {
  console.log(`\n  ${banner("deploy")}\n`);
  const known = Object.keys(targets).join("|");
  if (!target || !targets[target]) {
    if (target) console.log(`  ${c.red(g.err)} unknown target "${target}"`);
    console.log(`  usage: borgo deploy init <${known}> [--force]\n`);
    return 1;
  }

  const { file, render, next } = targets[target];
  const path = join(dir, file);
  if (existsSync(path) && !force) {
    console.log(`  ${c.red(g.err)} ${file} already exists ${c.dim(`${g.dot} rerun with --force to overwrite`)}\n`);
    return 1;
  }

  const ctx = projectContext(dir);
  try {
    writeFileSync(path, render(ctx));
  } catch (error) {
    console.log(`  ${c.red(g.err)} cannot write ${file}: ${error instanceof Error ? error.message : error}\n`);
    return 1;
  }
  console.log(`  ${c.sage(g.ok)} ${file} ${c.dim(`${g.dot} ${target} config for ${ctx.name} on port ${ctx.port}`)}`);
  console.log(`  ${c.terracotta(g.arrow)} ${next(ctx)}\n`);
  return 0;
}
