// borgo pwa init: writes the two files a progressive web app needs into
// public/, plus the line to add to a page. the service worker it generates is
// keyed on the precache stamp `borgo build` emits, so a deploy invalidates the
// cache and an unchanged rebuild does not.
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { banner, c, g } from "./colors";
import { projectContext } from "./deploy";

export function manifest(name: string): string {
  return (
    JSON.stringify(
      {
        name,
        short_name: name.length > 12 ? name.slice(0, 12) : name,
        description: `${name}, a borgo app`,
        start_url: "/",
        scope: "/",
        display: "standalone",
        background_color: "#f7f0e3",
        theme_color: "#c06b45",
        icons: [
          { src: "/logo.svg", sizes: "any", type: "image/svg+xml", purpose: "any" },
          { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
          { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
        ],
      },
      null,
      2,
    ) + "\n"
  );
}

// cache-first for build output only. documents are deliberately left alone:
// they are session-dependent and served no-store, and a blanket document
// cache is how one user ends up looking at another user's page.
export function serviceWorker(): string {
  return `// generated by borgo pwa init - yours to edit
// caches the build output listed in /assets/precache.json, keyed on the
// stamp that changes whenever any of that content changes.

const MANIFEST = "/assets/precache.json";

async function currentStamp() {
  const res = await fetch(MANIFEST, { cache: "no-store" });
  return res.json();
}

self.addEventListener("install", (event) => {
  event.waitUntil(
    currentStamp().then(({ stamp, assets }) =>
      caches.open("app-" + stamp).then((cache) => cache.addAll(assets)),
    ),
  );
  // take over as soon as this worker is ready rather than waiting for every
  // tab to close; the new cache is already filled by the time it happens
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    currentStamp()
      .then(({ stamp }) =>
        caches.keys().then((keys) =>
          Promise.all(
            keys
              .filter((key) => key.startsWith("app-") && key !== "app-" + stamp)
              .map((key) => caches.delete(key)),
          ),
        ),
      )
      .then(() => self.clients.claim()),
  );
});

self.addEventListener("fetch", (event) => {
  const url = new URL(event.request.url);
  // build output only: same origin, under /assets, and never the manifest
  // itself - a stale manifest would pin the app to an old stamp forever
  if (
    event.request.method !== "GET" ||
    url.origin !== location.origin ||
    !url.pathname.startsWith("/assets/") ||
    url.pathname === MANIFEST
  ) {
    return;
  }
  event.respondWith(caches.match(event.request).then((hit) => hit ?? fetch(event.request)));
});
`;
}

export function pwaInit(force = false, dir = "."): number {
  console.log(`\n  ${banner("pwa")}\n`);
  const ctx = projectContext(dir);
  const publicDir = join(dir, "public");
  try {
    mkdirSync(publicDir, { recursive: true });
  } catch {}

  const files: Array<[string, string]> = [
    ["manifest.webmanifest", manifest(ctx.name)],
    ["sw.js", serviceWorker()],
  ];

  const existing = files.filter(([f]) => existsSync(join(publicDir, f))).map(([f]) => f);
  if (existing.length && !force) {
    console.log(
      `  ${c.red(g.err)} public/${existing.join(", public/")} already exists ${c.dim(`${g.dot} rerun with --force to overwrite`)}\n`,
    );
    return 1;
  }

  for (const [file, contents] of files) {
    try {
      writeFileSync(join(publicDir, file), contents);
    } catch (error) {
      console.log(
        `  ${c.red(g.err)} cannot write public/${file}: ${error instanceof Error ? error.message : error}\n`,
      );
      return 1;
    }
    console.log(`  ${c.sage(g.ok)} public/${file}`);
  }

  console.log(`
  ${c.bold("two edits left")}, both one line:

  ${c.dim("1.")} in ${c.bold("index.html")}, inside <head>:
     ${c.terracotta('<link rel="manifest" href="/manifest.webmanifest" />')}

  ${c.dim("2.")} in a page or layout that hydrates:
     ${c.terracotta('import { registerServiceWorker } from "borgo-framework";')}
     ${c.terracotta("useEffect(() => registerServiceWorker(), []);")}

  ${c.dim(`the worker only runs in production builds ${g.dot} icons: add public/icon-192.png and icon-512.png`)}
  ${c.terracotta(g.arrow)} docs: https://github.com/LuigiDavideMicca/borgo/blob/main/docs/pwa.md
`);
  return 0;
}
