// generated by borgogen - do not edit

export interface Greeting {
  message: string;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/hello": { response: Greeting };
  }
}

export {};
