// generated by borgogen - do not edit
package api

import "github.com/LuigiDavideMicca/borgo"

func init() {
	borgo.Handle("GET /api/child", GetChild)
	borgo.Handle("GET /api/diamond", GetDiamond)
	borgo.Handle("GET /api/doc", GetDoc)
	borgo.Handle("GET /api/tie", GetTie)
}
