// generated by borgogen - do not edit

export interface Child {
  name: string;
  id: number;
}

export interface Diamond {
  a1: number;
  b1: number;
}

export interface Doc {
  id: number;
  name: string;
  title: string;
}

export interface Tie {
  y: number;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/child": { response: Child };
    "GET /api/diamond": { response: Diamond };
    "GET /api/doc": { response: Doc };
    "GET /api/tie": { response: Tie };
  }
}

export {};
