// generated by borgogen - do not edit

export interface Category {
  name: string;
  children?: Array<Category>;
  parent: Category | null;
}

export interface Export {
  payload: string;
}

export interface Health {
  status: string;
  detail?: string;
}

export interface FullHealth {
  status: string;
  detail?: string;
  uptime: number;
}

export interface Deleted {
  ok: boolean;
}

export interface Widget {
  created: string;
  id: number;
  name: string;
  tags?: Array<string>;
  price: string;
  notes: string | null;
  attrs: Record<string, number>;
  raw: unknown;
  counts: Record<string, string>;
  flags: unknown;
}

export interface WidgetList {
  widgets: Array<Widget>;
}

export interface WidgetCreate {
  name: string;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/categories": { response: Array<Category> };
    "GET /api/export": { response: Export };
    "GET /api/health": { response: Health };
    "GET /api/health/full": { response: FullHealth };
    "GET /api/manual": { response: string };
    "GET /api/secret": { response: Deleted };
    "GET /api/widgets": { response: WidgetList };
    "POST /api/widgets": { response: Widget; request: WidgetCreate };
    "DELETE /api/widgets/{id}": { response: Deleted };
    "GET /api/widgets/{id}": { response: Widget };
    "PUT /api/widgets/{id}": { response: Widget; request: WidgetCreate };
  }
  interface WsEvents {
    "widgets/created": Widget;
    "widgets/deleted": number | string;
  }
}

export {};
