// generated by borgogen - do not edit

export interface Greeting {
  message: string;
}

export interface GreetRequest {
  name: string;
}

declare module "borgo-framework" {
  interface ApiRoutes {
    "GET /api/events": { response: unknown };
    "GET /api/hello": { response: Greeting };
    "POST /api/hello": { response: Greeting; request: GreetRequest };
    "GET /api/hello/{name}": { response: Greeting };
  }
}

export {};
