// generated by borgogen - do not edit
package api

import "github.com/LuigiDavideMicca/borgo"

func init() {
	borgo.Handle("DELETE /api/widgets/{id}", DeleteWidget)
	borgo.Handle("GET /api/export", ExportWidgets)
	borgo.Handle("GET /api/health", HealthCheck)
	borgo.Handle("GET /api/widgets", ListWidgets)
	borgo.Handle("GET /api/widgets/{id}", GetWidget)
	borgo.Handle("POST /api/widgets", CreateWidget)
	borgo.Handle("PUT /api/widgets/{id}", UpdateWidget)
}
