// generated by borgogen - do not edit
package api

import "github.com/LuigiDavideMicca/borgo"

func init() {
	borgo.Handle("DELETE /api/widgets/{id}", DeleteWidget)
	borgo.Handle("GET /api/widgets", ListWidgets)
	borgo.Handle("POST /api/widgets", CreateWidget)
}
